[project]
name = "lab2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.3"
dependencies = [
    "jaxtyping>=0.3.9",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
]
